version: 2

jobs:
  build:
    working_directory: ~/core.typed
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: brew install clojure
      - run: ./script/test-all
