(ns clojure.core.typed.test.rt-infer.loop
  {:lang :core.typed
   :core.typed {:features #{#_:runtime-infer}}}
  (:require [clojure.core.typed :as t]))

;; Start: Generated by clojure.core.typed - DO NOT EDIT
(declare)
(t/ann b [(t/Vec Long) :-> (t/Vec Long)])
;; End: Generated by clojure.core.typed - DO NOT EDIT

(defn b [coll]
  (loop [^{::t/ann (t/U nil (t/Coll Long) (t/Vec Long))} c coll, ^{::t/ann (t/Vec Long)} out []]
    (if (seq c)
      (recur (next c) (conj out (inc (first c))))
      out)))

(b [1 2 3 4 5])

;(defn c [coll]
;  (loop [[:as c] coll
;         out []
;         {:as nothing} {}]
;    (if (seq c)
;      (recur (next c) (conj out (inc (first c))) nil)
;      out)))
;
;(c [1 2 3 4 5])

(doall
  (for ^{::t/ann (t/Vec Long)} 
    [^{::t/ann Long} a [1 2]
     ^{::t/ann Long} b [2 3]]
    [a b])
  )
