(ns clojure.core.typed.test.rt-infer.vector
  {:lang :core.typed
   :core.typed {:features #{:runtime-infer}}}
  (:require [clojure.core.typed :as t]))

;; Start: Generated by clojure.core.typed - DO NOT EDIT
(declare)
(t/ann b [(t/Vec t/Int) :-> (t/Vec t/Int)])
;; End: Generated by clojure.core.typed - DO NOT EDIT
(defn b [coll]
  (if (< 0.5 (rand))
    [1 2 3]
    [1 2 3 4]))

(dotimes [^{::t/ann t/Int} ^{::t/ann t/Int} _ 10]
  (b (vec (repeat (int (* 10 (rand) )) 10))))